### ISSUE TITLE
Hello Tyler, i have an issue regarding your project

### ISSUE THREAD

**Issue by bhanutejayada** [xTVaser/sr_discord_bot#61]
Hello tyler, i have been looking into your project, this is the link

https://github.com/xTVaser/web-threat-thesis

i have understood how to use testgenerator.py, but i cant move from that point, iam just struck, iam new to machine learning

i want to extend this project, and submit as my college project, it would be really helpful, if you find time to talk with me, or give me anything to contact you(like facebook\whatsapp)

iam sorry because of creating this in different repository, i need your help so badly, so please kindly understand my intent

Regards
Bhanu Teja Yada

**Comment by xTVaser** [comment]
Hey,

Unfortunately as I said before I havn't even looked at the code in over 2 years, I would have to look over it again completely to understand what the potential problems are you are running into and I really don't have any extra time to dedicate to doing so.

Please understand that the code was explicitly tailored to running the specific tests / gathering the results I needed; it was not written to be an extensible or a generic framework.  Meaning that for your college project you would most likely have to write everything from scratch if you are doing something unique.

You seem to have hit a roadblock, and if my project is that critical to your college project then I think I would have to recommend you pivoting and see if you can adjust your topic to something that is feasible.  

If you want to explore machine learning concepts then I'd recommend staying far away from my from-scratch-implementation / older libraries and checking out more modern projects such as https://www.tensorflow.org/tutorials/. Not only is it more modern, but you can find tons of tutorials all over that should help you create a solid final project.

Best of luck and sorry I can't offer any help.
